<?php

namespace Tests\PureOSC\SslCrypto;

use PureOSC\SslCrypto\SslDecryptSessionPassword;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-04-16 at 03:56:15.
 */
class SslDecryptSessionPasswordTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var SslDecryptSessionPassword
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new SslDecryptSessionPassword;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * @covers PureOSC\SslCrypto\SslDecryptSessionPassword::decrypt_session_password
   * @todo   Implement testDecrypt_session_password().
   */
  public function testDecrypt_session_password() {

    $this->assertEquals('test', SslDecryptSessionPassword::decrypt_session_password('test'));
  }

}
