<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:28.
 */
class Fwr_Media_Security_ProTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Fwr_Media_Security_Pro
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Fwr_Media_Security_Pro;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Fwr_Media_Security_Pro::Fwr_Media_Security_Pro
     * @todo   Implement testFwr_Media_Security_Pro().
     */
    public function testFwr_Media_Security_Pro()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fwr_Media_Security_Pro::addExclusion
     * @todo   Implement testAddExclusion().
     */
    public function testAddExclusion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fwr_Media_Security_Pro::addExclusions
     * @todo   Implement testAddExclusions().
     */
    public function testAddExclusions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fwr_Media_Security_Pro::cleanse
     * @todo   Implement testCleanse().
     */
    public function testCleanse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fwr_Media_Security_Pro::cleanseGetRecursive
     * @todo   Implement testCleanseGetRecursive().
     */
    public function testCleanseGetRecursive()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fwr_Media_Security_Pro::cleanseKeyString
     * @todo   Implement testCleanseKeyString().
     */
    public function testCleanseKeyString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fwr_Media_Security_Pro::cleanseValueString
     * @todo   Implement testCleanseValueString().
     */
    public function testCleanseValueString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fwr_Media_Security_Pro::cleanGlobals
     * @todo   Implement testCleanGlobals().
     */
    public function testCleanGlobals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
