<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:26:02.
 */
class cfgm_order_totalTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var cfgm_order_total
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new cfgm_order_total;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers cfgm_order_total::cfgm_order_total
     * @todo   Implement testCfgm_order_total().
     */
    public function testCfgm_order_total()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
