<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:26:02.
 */
class cfgm_social_bookmarksTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var cfgm_social_bookmarks
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new cfgm_social_bookmarks;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers cfgm_social_bookmarks::cfgm_social_bookmarks
     * @todo   Implement testCfgm_social_bookmarks().
     */
    public function testCfgm_social_bookmarks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
