<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:26:03.
 */
class cfgm_shippingTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var cfgm_shipping
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new cfgm_shipping;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers cfgm_shipping::cfgm_shipping
     * @todo   Implement testCfgm_shipping().
     */
    public function testCfgm_shipping()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
