<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:26:03.
 */
class cfgm_paymentTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var cfgm_payment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new cfgm_payment;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers cfgm_payment::cfgm_payment
     * @todo   Implement testCfgm_payment().
     */
    public function testCfgm_payment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
