<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:41.
 */
class navigationHistoryTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var navigationHistory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new navigationHistory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers navigationHistory::navigationHistory
     * @todo   Implement testNavigationHistory().
     */
    public function testNavigationHistory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers navigationHistory::reset
     * @todo   Implement testReset().
     */
    public function testReset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers navigationHistory::add_current_page
     * @todo   Implement testAdd_current_page().
     */
    public function testAdd_current_page()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers navigationHistory::remove_current_page
     * @todo   Implement testRemove_current_page().
     */
    public function testRemove_current_page()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers navigationHistory::set_snapshot
     * @todo   Implement testSet_snapshot().
     */
    public function testSet_snapshot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers navigationHistory::clear_snapshot
     * @todo   Implement testClear_snapshot().
     */
    public function testClear_snapshot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers navigationHistory::set_path_as_snapshot
     * @todo   Implement testSet_path_as_snapshot().
     */
    public function testSet_path_as_snapshot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers navigationHistory::debug
     * @todo   Implement testDebug().
     */
    public function testDebug()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers navigationHistory::filter_parameters
     * @todo   Implement testFilter_parameters().
     */
    public function testFilter_parameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers navigationHistory::unserialize
     * @todo   Implement testUnserialize().
     */
    public function testUnserialize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
