<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:43.
 */
class oscTemplateTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var oscTemplate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new oscTemplate;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers oscTemplate::oscTemplate
     * @todo   Implement testOscTemplate().
     */
    public function testOscTemplate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers oscTemplate::setGridContainerWidth
     * @todo   Implement testSetGridContainerWidth().
     */
    public function testSetGridContainerWidth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers oscTemplate::getGridContainerWidth
     * @todo   Implement testGetGridContainerWidth().
     */
    public function testGetGridContainerWidth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers oscTemplate::setGridContentWidth
     * @todo   Implement testSetGridContentWidth().
     */
    public function testSetGridContentWidth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers oscTemplate::getGridContentWidth
     * @todo   Implement testGetGridContentWidth().
     */
    public function testGetGridContentWidth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers oscTemplate::setGridColumnWidth
     * @todo   Implement testSetGridColumnWidth().
     */
    public function testSetGridColumnWidth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers oscTemplate::getGridColumnWidth
     * @todo   Implement testGetGridColumnWidth().
     */
    public function testGetGridColumnWidth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers oscTemplate::setTitle
     * @todo   Implement testSetTitle().
     */
    public function testSetTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers oscTemplate::getTitle
     * @todo   Implement testGetTitle().
     */
    public function testGetTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers oscTemplate::addBlock
     * @todo   Implement testAddBlock().
     */
    public function testAddBlock()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers oscTemplate::hasBlocks
     * @todo   Implement testHasBlocks().
     */
    public function testHasBlocks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers oscTemplate::getBlocks
     * @todo   Implement testGetBlocks().
     */
    public function testGetBlocks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers oscTemplate::buildBlocks
     * @todo   Implement testBuildBlocks().
     */
    public function testBuildBlocks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers oscTemplate::addContent
     * @todo   Implement testAddContent().
     */
    public function testAddContent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers oscTemplate::hasContent
     * @todo   Implement testHasContent().
     */
    public function testHasContent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers oscTemplate::getContent
     * @todo   Implement testGetContent().
     */
    public function testGetContent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers oscTemplate::getContentModules
     * @todo   Implement testGetContentModules().
     */
    public function testGetContentModules()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
