<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:42.
 */
class SEO_DataBaseTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var SEO_DataBase
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SEO_DataBase;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers SEO_DataBase::SEO_DataBase
     * @todo   Implement testSEO_DataBase().
     */
    public function testSEO_DataBase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SEO_DataBase::ConnectDB
     * @todo   Implement testConnectDB().
     */
    public function testConnectDB()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SEO_DataBase::Query
     * @todo   Implement testQuery().
     */
    public function testQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SEO_DataBase::FetchArray
     * @todo   Implement testFetchArray().
     */
    public function testFetchArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SEO_DataBase::NumRows
     * @todo   Implement testNumRows().
     */
    public function testNumRows()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SEO_DataBase::InsertID
     * @todo   Implement testInsertID().
     */
    public function testInsertID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SEO_DataBase::Free
     * @todo   Implement testFree().
     */
    public function testFree()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SEO_DataBase::Slashes
     * @todo   Implement testSlashes().
     */
    public function testSlashes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SEO_DataBase::DBPerform
     * @todo   Implement testDBPerform().
     */
    public function testDBPerform()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
