<?php

namespace PureOSC;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:43.
 */
class SeoUrlTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var SeoUrl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SeoUrl;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers PureOSC\SeoUrl::href_link
     * @todo   Implement testHref_link().
     */
    public function testHref_link()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::stock_href_link
     * @todo   Implement testStock_href_link().
     */
    public function testStock_href_link()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::add_sid
     * @todo   Implement testAdd_sid().
     */
    public function testAdd_sid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::parse_parameters
     * @todo   Implement testParse_parameters().
     */
    public function testParse_parameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::make_url
     * @todo   Implement testMake_url().
     */
    public function testMake_url()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_product_name
     * @todo   Implement testGet_product_name().
     */
    public function testGet_product_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_all_category_parents
     * @todo   Implement testGet_all_category_parents().
     */
    public function testGet_all_category_parents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_all_category_names
     * @todo   Implement testGet_all_category_names().
     */
    public function testGet_all_category_names()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_category_name
     * @todo   Implement testGet_category_name().
     */
    public function testGet_category_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_manufacturer_name
     * @todo   Implement testGet_manufacturer_name().
     */
    public function testGet_manufacturer_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_all_topics_parents
     * @todo   Implement testGet_all_topics_parents().
     */
    public function testGet_all_topics_parents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_all_topics_names
     * @todo   Implement testGet_all_topics_names().
     */
    public function testGet_all_topics_names()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_article_name
     * @todo   Implement testGet_article_name().
     */
    public function testGet_article_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_authors_name
     * @todo   Implement testGet_authors_name().
     */
    public function testGet_authors_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_topic_name
     * @todo   Implement testGet_topic_name().
     */
    public function testGet_topic_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_faqdesk_name
     * @todo   Implement testGet_faqdesk_name().
     */
    public function testGet_faqdesk_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_faqdesk_categories_name
     * @todo   Implement testGet_faqdesk_categories_name().
     */
    public function testGet_faqdesk_categories_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_link_name
     * @todo   Implement testGet_link_name().
     */
    public function testGet_link_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_information_name
     * @todo   Implement testGet_information_name().
     */
    public function testGet_information_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_page_editor_name
     * @todo   Implement testGet_page_editor_name().
     */
    public function testGet_page_editor_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_pollbooth
     * @todo   Implement testGet_pollbooth().
     */
    public function testGet_pollbooth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_newsdesk_name
     * @todo   Implement testGet_newsdesk_name().
     */
    public function testGet_newsdesk_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_newsdesk_categories_name
     * @todo   Implement testGet_newsdesk_categories_name().
     */
    public function testGet_newsdesk_categories_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_full_cPath
     * @todo   Implement testGet_full_cPath().
     */
    public function testGet_full_cPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::GetParentCategories
     * @todo   Implement testGetParentCategories().
     */
    public function testGetParentCategories()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::GetParentTopics
     * @todo   Implement testGetParentTopics().
     */
    public function testGetParentTopics()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::not_null
     * @todo   Implement testNot_null().
     */
    public function testNot_null()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::is_attribute_string
     * @todo   Implement testIs_attribute_string().
     */
    public function testIs_attribute_string()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::is_product_string
     * @todo   Implement testIs_product_string().
     */
    public function testIs_product_string()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::is_cPath_string
     * @todo   Implement testIs_cPath_string().
     */
    public function testIs_cPath_string()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::profile
     * @todo   Implement testProfile().
     */
    public function testProfile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::calculate_performance
     * @todo   Implement testCalculate_performance().
     */
    public function testCalculate_performance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::strip
     * @todo   Implement testStrip().
     */
    public function testStrip()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::expand
     * @todo   Implement testExpand().
     */
    public function testExpand()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::short_name
     * @todo   Implement testShort_name().
     */
    public function testShort_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::implode_assoc
     * @todo   Implement testImplode_assoc().
     */
    public function testImplode_assoc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::PrintArray
     * @todo   Implement testPrintArray().
     */
    public function testPrintArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::start
     * @todo   Implement testStart().
     */
    public function testStart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::stop
     * @todo   Implement testStop().
     */
    public function testStop()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::parse_input_field_data
     * @todo   Implement testParse_input_field_data().
     */
    public function testParse_input_field_data()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::output_string
     * @todo   Implement testOutput_string().
     */
    public function testOutput_string()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::SessionID
     * @todo   Implement testSessionID().
     */
    public function testSessionID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::SessionName
     * @todo   Implement testSessionName().
     */
    public function testSessionName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::generate_products_cache
     * @todo   Implement testGenerate_products_cache().
     */
    public function testGenerate_products_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::generate_manufacturers_cache
     * @todo   Implement testGenerate_manufacturers_cache().
     */
    public function testGenerate_manufacturers_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::generate_categories_cache
     * @todo   Implement testGenerate_categories_cache().
     */
    public function testGenerate_categories_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::generate_articles_cache
     * @todo   Implement testGenerate_articles_cache().
     */
    public function testGenerate_articles_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::generate_articles_authors_cache
     * @todo   Implement testGenerate_articles_authors_cache().
     */
    public function testGenerate_articles_authors_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::generate_topics_cache
     * @todo   Implement testGenerate_topics_cache().
     */
    public function testGenerate_topics_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::generate_faqdesk_categories_cache
     * @todo   Implement testGenerate_faqdesk_categories_cache().
     */
    public function testGenerate_faqdesk_categories_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::generate_links_cache
     * @todo   Implement testGenerate_links_cache().
     */
    public function testGenerate_links_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::generate_information_cache
     * @todo   Implement testGenerate_information_cache().
     */
    public function testGenerate_information_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::generate_newsdesk_name_cache
     * @todo   Implement testGenerate_newsdesk_name_cache().
     */
    public function testGenerate_newsdesk_name_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::generate_newsdesk_categories_cache
     * @todo   Implement testGenerate_newsdesk_categories_cache().
     */
    public function testGenerate_newsdesk_categories_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::generate_page_editor_cache
     * @todo   Implement testGenerate_page_editor_cache().
     */
    public function testGenerate_page_editor_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::generate_pollbooth_cache
     * @todo   Implement testGenerate_pollbooth_cache().
     */
    public function testGenerate_pollbooth_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::save_cache
     * @todo   Implement testSave_cache().
     */
    public function testSave_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_cache
     * @todo   Implement testGet_cache().
     */
    public function testGet_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::get_cache_memory
     * @todo   Implement testGet_cache_memory().
     */
    public function testGet_cache_memory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::cache_gc
     * @todo   Implement testCache_gc().
     */
    public function testCache_gc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::convert_time
     * @todo   Implement testConvert_time().
     */
    public function testConvert_time()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::is_cached
     * @todo   Implement testIs_cached().
     */
    public function testIs_cached()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::check_redirect
     * @todo   Implement testCheck_redirect().
     */
    public function testCheck_redirect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::turnOffBrokenUrls
     * @todo   Implement testTurnOffBrokenUrls().
     */
    public function testTurnOffBrokenUrls()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::need_redirect
     * @todo   Implement testNeed_redirect().
     */
    public function testNeed_redirect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::VerifyLink
     * @todo   Implement testVerifyLink().
     */
    public function testVerifyLink()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::check_seo_page
     * @todo   Implement testCheck_seo_page().
     */
    public function testCheck_seo_page()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::parse_path
     * @todo   Implement testParse_path().
     */
    public function testParse_path()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::do_redirect
     * @todo   Implement testDo_redirect().
     */
    public function testDo_redirect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrl::remove_accents
     * @todo   Implement testRemove_accents().
     */
    public function testRemove_accents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
