<?php

namespace PureOSC;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:45.
 */
class SeoUrlInstallerTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var SeoUrlInstaller
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SeoUrlInstaller;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers PureOSC\SeoUrlInstaller::init
     * @todo   Implement testInit().
     */
    public function testInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrlInstaller::eval_defaults
     * @todo   Implement testEval_defaults().
     */
    public function testEval_defaults()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrlInstaller::uninstall_settings
     * @todo   Implement testUninstall_settings().
     */
    public function testUninstall_settings()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PureOSC\SeoUrlInstaller::install_settings
     * @todo   Implement testInstall_settings().
     */
    public function testInstall_settings()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
