<?php

namespace Test\PureOSC;

use PureOSC\SslCrypto;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-04-22 at 21:30:26.
 */
class SslCryptoTest extends \PHPUnit_Framework_TestCase {

  public $crypted = null;

  /**
   * @var SslCrypto
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new SslCrypto;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * @covers PureOSC\SslCrypto::encrypt
   * @covers PureOSC\SslCrypto::decrypt
   */
  public function testEncryptDecrypt() {
    $plaintext = 'slovo plaintext';
    $crypted = SslCrypto::encrypt($plaintext, 1);
    $crypted_password = SslCrypto::encrypt_session_password('testshop');
    $this->assertEquals($plaintext, SslCrypto::decrypt($crypted, $crypted_password, 1));
  }

  /**
   * @covers PureOSC\SslCrypto::encrypt_session_password
   * @todo   Implement testEncrypt_session_password().
   */
  public function testEncrypt_session_password() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers PureOSC\SslCrypto::decrypt_session_password
   * @todo   Implement testDecrypt_session_password().
   */
  public function testDecrypt_session_password() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers PureOSC\SslCrypto::crypto_fu
   * @todo   Implement testCrypto_fu().
   */
  public function testCrypto_fu() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers PureOSC\SslCrypto::change_passphrase_customer
   * @todo   Implement testChange_passphrase_customer().
   */
  public function testChange_passphrase_customer() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers PureOSC\SslCrypto::generate_customer_keys
   * @todo   Implement testGenerate_customer_keys().
   */
  public function testGenerate_customer_keys() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

}
