filter:
    excluded_paths:
        - 'tests/*'
        - 'vendor/*'
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"

checks:
    php:
        code_rating: true
        duplication: true
        
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: './vendor/bin/phpunit --coverage-clover=coverage.xml'
            coverage:
              file: coverage.xml
              format: clover


    dependencies:
        before:
            - mysql -u root -e "CREATE DATABASE pureosc"
            - mysql -u root -e "GRANT ALL PRIVILEGES ON pureosc.* TO pureosc@localhost IDENTIFIED BY 'pureosc'"
            - sudo -u postgres bash -c "psql -c \"CREATE USER pureosc WITH PASSWORD 'pureosc';\""
            - sudo -u postgres bash -c "psql -c \"create database pureosc with owner pureosc encoding='utf8' template template0;\""
            - composer self-update
            - composer install --no-interaction
            - ./vendor/bin/phinx seed:run -s Oscommerce -c ./phinx-adapter.php
            - ./vendor/bin/phinx migrate -c ./phinx-adapter.php
