<?php
/*
  $Id: cm_fp_carousel.php, v1.0 20160129 Kymation$

  osCommerce, Open Source E-Commerce Solutions
  http://www.oscommerce.com

  Copyright (c) 2016 James C Keebaugh

  Released under the GNU General Public License v2.0 or later
 */
?>

<!-- Start cm_fp_carousel module -->
<div class="contentContainer">
    <div id="rotator" class="col-sm-<?php echo MODULE_CONTENT_FRONT_PAGE_MANUFACTURERS_CONTENT_WIDTH; ?>">
        <div class="slideshow">
            <div class="wrapper">
                <div class="slides">
                    <?php
                    foreach ($manufacturers_data as $banner) {
                        ?>

                        <div class="slide">
                            <?php
                            if ($banner['manufacturers_url'] == '') {
                                echo '<p>';
                            } else {
                                echo '<a href="'.$banner['manufacturers_url'].'">';
                            }

                            echo tep_image(DIR_WS_IMAGES.$banner['manufacturers_image'],
                                $banner['manufacturers_html_text']);

                            if ($banner['manufacturers_url'] == '') {
                                echo '</p>';
                            } else {
                                echo '</a>';
                            }
                            ?>
                        </div>
                        <?php
                    }
                    ?>
                </div>
            </div>
            <div class="slideTabs">
                <!-- content generated by js -->
            </div>
            <span class="next"><img src="images/slideshow/next4.png" alt="Next" /></span>
            <span class="prev"><img src="images/slideshow/prev4.png" alt="Previous" /></span>				
        </div>          
    </div>
</div>
<!-- End cm_fp_carousel module -->