<?php

namespace kcfinder;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:49.
 */
class imageTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var image
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new image;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers kcfinder\image::__get
     * @todo   Implement test__get().
     */
    public function test__get()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers kcfinder\image::factory
     * @todo   Implement testFactory().
     */
    public function testFactory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers kcfinder\image::getDriver
     * @todo   Implement testGetDriver().
     */
    public function testGetDriver()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers kcfinder\image::getPropWidth
     * @todo   Implement testGetPropWidth().
     */
    public function testGetPropWidth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers kcfinder\image::getPropHeight
     * @todo   Implement testGetPropHeight().
     */
    public function testGetPropHeight()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers kcfinder\image::available
     * @todo   Implement testAvailable().
     */
    public function testAvailable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers kcfinder\image::checkImage
     * @todo   Implement testCheckImage().
     */
    public function testCheckImage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
