<?php

namespace kcfinder;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:48.
 */
class pathTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var path
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new path;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers kcfinder\path::rel2abs_url
     * @todo   Implement testRel2abs_url().
     */
    public function testRel2abs_url()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers kcfinder\path::url2fullPath
     * @todo   Implement testUrl2fullPath().
     */
    public function testUrl2fullPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers kcfinder\path::normalize
     * @todo   Implement testNormalize().
     */
    public function testNormalize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers kcfinder\path::urlPathEncode
     * @todo   Implement testUrlPathEncode().
     */
    public function testUrlPathEncode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers kcfinder\path::urlPathDecode
     * @todo   Implement testUrlPathDecode().
     */
    public function testUrlPathDecode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
