<?php

namespace kcfinder;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:50.
 */
class textTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var text
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new text;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers kcfinder\text::clearWhitespaces
     * @todo   Implement testClearWhitespaces().
     */
    public function testClearWhitespaces()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers kcfinder\text::htmlValue
     * @todo   Implement testHtmlValue().
     */
    public function testHtmlValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers kcfinder\text::jsValue
     * @todo   Implement testJsValue().
     */
    public function testJsValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
