<?php

namespace kcfinder;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:49.
 */
class fileTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var file
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new file;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers kcfinder\file::isWritable
     * @todo   Implement testIsWritable().
     */
    public function testIsWritable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers kcfinder\file::getExtension
     * @todo   Implement testGetExtension().
     */
    public function testGetExtension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers kcfinder\file::getMimeType
     * @todo   Implement testGetMimeType().
     */
    public function testGetMimeType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers kcfinder\file::getInexistantFilename
     * @todo   Implement testGetInexistantFilename().
     */
    public function testGetInexistantFilename()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers kcfinder\file::normalizeFilename
     * @todo   Implement testNormalizeFilename().
     */
    public function testNormalizeFilename()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
