<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:58.
 */
class securityCheck_download_directoryTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var securityCheck_download_directory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new securityCheck_download_directory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers securityCheck_download_directory::securityCheck_download_directory
     * @todo   Implement testSecurityCheck_download_directory().
     */
    public function testSecurityCheck_download_directory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers securityCheck_download_directory::pass
     * @todo   Implement testPass().
     */
    public function testPass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers securityCheck_download_directory::getMessage
     * @todo   Implement testGetMessage().
     */
    public function testGetMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
