<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:58.
 */
class securityCheck_extended_last_runTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var securityCheck_extended_last_run
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new securityCheck_extended_last_run;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers securityCheck_extended_last_run::securityCheck_extended_last_run
     * @todo   Implement testSecurityCheck_extended_last_run().
     */
    public function testSecurityCheck_extended_last_run()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers securityCheck_extended_last_run::pass
     * @todo   Implement testPass().
     */
    public function testPass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers securityCheck_extended_last_run::getMessage
     * @todo   Implement testGetMessage().
     */
    public function testGetMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
