<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:57.
 */
class securityCheck_file_uploadsTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var securityCheck_file_uploads
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new securityCheck_file_uploads;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers securityCheck_file_uploads::securityCheck_file_uploads
     * @todo   Implement testSecurityCheck_file_uploads().
     */
    public function testSecurityCheck_file_uploads()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers securityCheck_file_uploads::pass
     * @todo   Implement testPass().
     */
    public function testPass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers securityCheck_file_uploads::getMessage
     * @todo   Implement testGetMessage().
     */
    public function testGetMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
