<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:58.
 */
class securityCheck_session_auto_startTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var securityCheck_session_auto_start
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new securityCheck_session_auto_start;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers securityCheck_session_auto_start::securityCheck_session_auto_start
     * @todo   Implement testSecurityCheck_session_auto_start().
     */
    public function testSecurityCheck_session_auto_start()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers securityCheck_session_auto_start::pass
     * @todo   Implement testPass().
     */
    public function testPass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers securityCheck_session_auto_start::getMessage
     * @todo   Implement testGetMessage().
     */
    public function testGetMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
