#pure:new Products admin values visible 
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Display products DateAvailable (expected)', 'DISPLAY_DATE_AVAILABLE', 'true', 'Display products DateAvailable (expected)?', '17', '1', 'tep_cfg_select_option(array(\'true\', \'false\'), ', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Display products custom date', 'DISPLAY_PRODUCTS_CUSTOM_DATE', 'true', 'Display products custom/events date?', '17', '2', 'tep_cfg_select_option(array(\'true\', \'false\'), ', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Display products sort order', 'DISPLAY_PRODUCTS_SORT_ORDER', 'true', 'Display products sort order?', '17', '3', 'tep_cfg_select_option(array(\'true\', \'false\'), ', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Display products manfacturer', 'DISPLAY_PRODUCTS_MANUFACTURER', 'true', 'Display products manfacturer', '17', '4', 'tep_cfg_select_option(array(\'true\', \'false\'), ', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Display products SEO title', 'DISPLAY_PRODUCTS_SEO_TITLE', 'true', 'Display products SEO title?', '17', '5', 'tep_cfg_select_option(array(\'true\', \'false\'), ', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Display Tax Class', 'DISPLAY_PRODUCTS_TAX_CLASS', 'true', 'Display Tax Class?', '17', '5', 'tep_cfg_select_option(array(\'true\', \'false\'), ', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Display Mini description', 'DISPLAY_PRODUCTS_MINI_DESCRIPTION', 'true', 'Display Mini description?', '17', '6', 'tep_cfg_select_option(array(\'true\', \'false\'), ', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Display products quantity', 'DISPLAY_PRODUCTS_QUANTITY', 'true', 'Display products quantity?', '17', '7', 'tep_cfg_select_option(array(\'true\', \'false\'), ', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Display products Model', 'DISPLAY_PRODUCTS_MODEL', 'true', 'Display products Model?', '17', '8', 'tep_cfg_select_option(array(\'true\', \'false\'), ', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Display products URL', 'DISPLAY_PRODUCTS_URL', 'true', 'Display products URL?', '17', '9', 'tep_cfg_select_option(array(\'true\', \'false\'), ', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Display products weight', 'DISPLAY_PRODUCTS_WEIGHT', 'true', 'Display products weight?', '17', '10', 'tep_cfg_select_option(array(\'true\', \'false\'), ', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Display products SEO description', 'DISPLAY_PRODUCTS_SEO_DESCRIPTION', 'true', 'Display products SEO description?', '17', '11', 'tep_cfg_select_option(array(\'true\', \'false\'), ', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Display products SEO keywords', 'DISPLAY_PRODUCTS_SEO_KEYWORDS', 'true', 'Display products SEO keywords?', '17', '12', 'tep_cfg_select_option(array(\'true\', \'false\'), ', now());

INSERT INTO configuration_group VALUES ('17', 'Products admin values visible','Define values in categories/product to be visible',17,1);
