<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:54.
 */
class PHPlotTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var PHPlot
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PHPlot;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers PHPlot::InitImage
     * @todo   Implement testInitImage().
     */
    public function testInitImage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetBrowserCache
     * @todo   Implement testSetBrowserCache().
     */
    public function testSetBrowserCache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPrintImage
     * @todo   Implement testSetPrintImage().
     */
    public function testSetPrintImage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetIsInline
     * @todo   Implement testSetIsInline().
     */
    public function testSetIsInline()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetUseTTF
     * @todo   Implement testSetUseTTF().
     */
    public function testSetUseTTF()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetTitleFontSize
     * @todo   Implement testSetTitleFontSize().
     */
    public function testSetTitleFontSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLineStyles
     * @todo   Implement testSetLineStyles().
     */
    public function testSetLineStyles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLegend
     * @todo   Implement testSetLegend().
     */
    public function testSetLegend()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLegendPixels
     * @todo   Implement testSetLegendPixels().
     */
    public function testSetLegendPixels()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLegendWorld
     * @todo   Implement testSetLegendWorld().
     */
    public function testSetLegendWorld()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetFileFormat
     * @todo   Implement testSetFileFormat().
     */
    public function testSetFileFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetInputFile
     * @todo   Implement testSetInputFile().
     */
    public function testSetInputFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetOutputFile
     * @todo   Implement testSetOutputFile().
     */
    public function testSetOutputFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetImageArea
     * @todo   Implement testSetImageArea().
     */
    public function testSetImageArea()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYAxisPosition
     * @todo   Implement testSetYAxisPosition().
     */
    public function testSetYAxisPosition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXAxisPosition
     * @todo   Implement testSetXAxisPosition().
     */
    public function testSetXAxisPosition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXTimeFormat
     * @todo   Implement testSetXTimeFormat().
     */
    public function testSetXTimeFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXDataLabelMaxlength
     * @todo   Implement testSetXDataLabelMaxlength().
     */
    public function testSetXDataLabelMaxlength()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXDataLabelAngle
     * @todo   Implement testSetXDataLabelAngle().
     */
    public function testSetXDataLabelAngle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXScaleType
     * @todo   Implement testSetXScaleType().
     */
    public function testSetXScaleType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYScaleType
     * @todo   Implement testSetYScaleType().
     */
    public function testSetYScaleType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPrecisionX
     * @todo   Implement testSetPrecisionX().
     */
    public function testSetPrecisionX()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPrecisionY
     * @todo   Implement testSetPrecisionY().
     */
    public function testSetPrecisionY()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetIndexColors
     * @todo   Implement testSetIndexColors().
     */
    public function testSetIndexColors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDefaultColors
     * @todo   Implement testSetDefaultColors().
     */
    public function testSetDefaultColors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::PrintImage
     * @todo   Implement testPrintImage().
     */
    public function testPrintImage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawBackground
     * @todo   Implement testDrawBackground().
     */
    public function testDrawBackground()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawImageBorder
     * @todo   Implement testDrawImageBorder().
     */
    public function testDrawImageBorder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPlotBorderType
     * @todo   Implement testSetPlotBorderType().
     */
    public function testSetPlotBorderType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetImageBorderType
     * @todo   Implement testSetImageBorderType().
     */
    public function testSetImageBorderType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDrawPlotAreaBackground
     * @todo   Implement testSetDrawPlotAreaBackground().
     */
    public function testSetDrawPlotAreaBackground()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDrawDataLabels
     * @todo   Implement testSetDrawDataLabels().
     */
    public function testSetDrawDataLabels()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDrawXDataLabels
     * @todo   Implement testSetDrawXDataLabels().
     */
    public function testSetDrawXDataLabels()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDrawYGrid
     * @todo   Implement testSetDrawYGrid().
     */
    public function testSetDrawYGrid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDrawXGrid
     * @todo   Implement testSetDrawXGrid().
     */
    public function testSetDrawXGrid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYGridLabelType
     * @todo   Implement testSetYGridLabelType().
     */
    public function testSetYGridLabelType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXGridLabelType
     * @todo   Implement testSetXGridLabelType().
     */
    public function testSetXGridLabelType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXLabel
     * @todo   Implement testSetXLabel().
     */
    public function testSetXLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYLabel
     * @todo   Implement testSetYLabel().
     */
    public function testSetYLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetTitle
     * @todo   Implement testSetTitle().
     */
    public function testSetTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawLabels
     * @todo   Implement testDrawLabels().
     */
    public function testDrawLabels()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawXLabel
     * @todo   Implement testDrawXLabel().
     */
    public function testDrawXLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawYLabel
     * @todo   Implement testDrawYLabel().
     */
    public function testDrawYLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawText
     * @todo   Implement testDrawText().
     */
    public function testDrawText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawTitle
     * @todo   Implement testDrawTitle().
     */
    public function testDrawTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawPlotAreaBackground
     * @todo   Implement testDrawPlotAreaBackground().
     */
    public function testDrawPlotAreaBackground()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetBackgroundColor
     * @todo   Implement testSetBackgroundColor().
     */
    public function testSetBackgroundColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPlotBgColor
     * @todo   Implement testSetPlotBgColor().
     */
    public function testSetPlotBgColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetShading
     * @todo   Implement testSetShading().
     */
    public function testSetShading()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetTitleColor
     * @todo   Implement testSetTitleColor().
     */
    public function testSetTitleColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetTickColor
     * @todo   Implement testSetTickColor().
     */
    public function testSetTickColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLabelColor
     * @todo   Implement testSetLabelColor().
     */
    public function testSetLabelColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetTextColor
     * @todo   Implement testSetTextColor().
     */
    public function testSetTextColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLightGridColor
     * @todo   Implement testSetLightGridColor().
     */
    public function testSetLightGridColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetGridColor
     * @todo   Implement testSetGridColor().
     */
    public function testSetGridColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetCharacterHeight
     * @todo   Implement testSetCharacterHeight().
     */
    public function testSetCharacterHeight()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPlotType
     * @todo   Implement testSetPlotType().
     */
    public function testSetPlotType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::FindDataLimits
     * @todo   Implement testFindDataLimits().
     */
    public function testFindDataLimits()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetMargins
     * @todo   Implement testSetMargins().
     */
    public function testSetMargins()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetMarginsPixels
     * @todo   Implement testSetMarginsPixels().
     */
    public function testSetMarginsPixels()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetNewPlotAreaPixels
     * @todo   Implement testSetNewPlotAreaPixels().
     */
    public function testSetNewPlotAreaPixels()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPlotAreaPixels
     * @todo   Implement testSetPlotAreaPixels().
     */
    public function testSetPlotAreaPixels()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPlotAreaWorld
     * @todo   Implement testSetPlotAreaWorld().
     */
    public function testSetPlotAreaWorld()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::PrintError
     * @todo   Implement testPrintError().
     */
    public function testPrintError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawError
     * @todo   Implement testDrawError().
     */
    public function testDrawError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::TTFBBoxSize
     * @todo   Implement testTTFBBoxSize().
     */
    public function testTTFBBoxSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetXLabelHeight
     * @todo   Implement testSetXLabelHeight().
     */
    public function testSetXLabelHeight()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetYLabelWidth
     * @todo   Implement testSetYLabelWidth().
     */
    public function testSetYLabelWidth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetEqualXCoord
     * @todo   Implement testSetEqualXCoord().
     */
    public function testSetEqualXCoord()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLabelScalePosition
     * @todo   Implement testSetLabelScalePosition().
     */
    public function testSetLabelScalePosition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetErrorBarSize
     * @todo   Implement testSetErrorBarSize().
     */
    public function testSetErrorBarSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetErrorBarShape
     * @todo   Implement testSetErrorBarShape().
     */
    public function testSetErrorBarShape()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPointShape
     * @todo   Implement testSetPointShape().
     */
    public function testSetPointShape()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetPointSize
     * @todo   Implement testSetPointSize().
     */
    public function testSetPointSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDataType
     * @todo   Implement testSetDataType().
     */
    public function testSetDataType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDataValues
     * @todo   Implement testSetDataValues().
     */
    public function testSetDataValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetRGBArray
     * @todo   Implement testSetRGBArray().
     */
    public function testSetRGBArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetColor
     * @todo   Implement testSetColor().
     */
    public function testSetColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetIndexColor
     * @todo   Implement testSetIndexColor().
     */
    public function testSetIndexColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetTransparentColor
     * @todo   Implement testSetTransparentColor().
     */
    public function testSetTransparentColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetRgbColor
     * @todo   Implement testSetRgbColor().
     */
    public function testSetRgbColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDataColors
     * @todo   Implement testSetDataColors().
     */
    public function testSetDataColors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetErrorBarColors
     * @todo   Implement testSetErrorBarColors().
     */
    public function testSetErrorBarColors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawPlotBorder
     * @todo   Implement testDrawPlotBorder().
     */
    public function testDrawPlotBorder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetHorizTickIncrement
     * @todo   Implement testSetHorizTickIncrement().
     */
    public function testSetHorizTickIncrement()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetDrawVertTicks
     * @todo   Implement testSetDrawVertTicks().
     */
    public function testSetDrawVertTicks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetVertTickIncrement
     * @todo   Implement testSetVertTickIncrement().
     */
    public function testSetVertTickIncrement()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetNumHorizTicks
     * @todo   Implement testSetNumHorizTicks().
     */
    public function testSetNumHorizTicks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetNumVertTicks
     * @todo   Implement testSetNumVertTicks().
     */
    public function testSetNumVertTicks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetVertTickPosition
     * @todo   Implement testSetVertTickPosition().
     */
    public function testSetVertTickPosition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetSkipBottomTick
     * @todo   Implement testSetSkipBottomTick().
     */
    public function testSetSkipBottomTick()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetTickLength
     * @todo   Implement testSetTickLength().
     */
    public function testSetTickLength()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawYAxis
     * @todo   Implement testDrawYAxis().
     */
    public function testDrawYAxis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawXAxis
     * @todo   Implement testDrawXAxis().
     */
    public function testDrawXAxis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawHorizontalTicks
     * @todo   Implement testDrawHorizontalTicks().
     */
    public function testDrawHorizontalTicks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::FormatYTickLabel
     * @todo   Implement testFormatYTickLabel().
     */
    public function testFormatYTickLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawVerticalTick
     * @todo   Implement testDrawVerticalTick().
     */
    public function testDrawVerticalTick()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawVerticalTicks
     * @todo   Implement testDrawVerticalTicks().
     */
    public function testDrawVerticalTicks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetTranslation
     * @todo   Implement testSetTranslation().
     */
    public function testSetTranslation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::xtr
     * @todo   Implement testXtr().
     */
    public function testXtr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::ytr
     * @todo   Implement testYtr().
     */
    public function testYtr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawDataLabel
     * @todo   Implement testDrawDataLabel().
     */
    public function testDrawDataLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawXDataLabel
     * @todo   Implement testDrawXDataLabel().
     */
    public function testDrawXDataLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawPieChart
     * @todo   Implement testDrawPieChart().
     */
    public function testDrawPieChart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawLinesError
     * @todo   Implement testDrawLinesError().
     */
    public function testDrawLinesError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawDotsError
     * @todo   Implement testDrawDotsError().
     */
    public function testDrawDotsError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawDots
     * @todo   Implement testDrawDots().
     */
    public function testDrawDots()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawDotSeries
     * @todo   Implement testDrawDotSeries().
     */
    public function testDrawDotSeries()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawThinBarLines
     * @todo   Implement testDrawThinBarLines().
     */
    public function testDrawThinBarLines()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawYErrorBar
     * @todo   Implement testDrawYErrorBar().
     */
    public function testDrawYErrorBar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawDot
     * @todo   Implement testDrawDot().
     */
    public function testDrawDot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetErrorBarLineWidth
     * @todo   Implement testSetErrorBarLineWidth().
     */
    public function testSetErrorBarLineWidth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::SetLineWidth
     * @todo   Implement testSetLineWidth().
     */
    public function testSetLineWidth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawArea
     * @todo   Implement testDrawArea().
     */
    public function testDrawArea()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawAreaSeries
     * @todo   Implement testDrawAreaSeries().
     */
    public function testDrawAreaSeries()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawLines
     * @todo   Implement testDrawLines().
     */
    public function testDrawLines()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawLineSeries
     * @todo   Implement testDrawLineSeries().
     */
    public function testDrawLineSeries()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawDashedLine
     * @todo   Implement testDrawDashedLine().
     */
    public function testDrawDashedLine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawBars
     * @todo   Implement testDrawBars().
     */
    public function testDrawBars()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawLegend
     * @todo   Implement testDrawLegend().
     */
    public function testDrawLegend()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPlot::DrawGraph
     * @todo   Implement testDrawGraph().
     */
    public function testDrawGraph()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
