<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:26:03.
 */
class manualCartTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var manualCart
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new manualCart;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers manualCart::manualCart
     * @todo   Implement testManualCart().
     */
    public function testManualCart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers manualCart::restore_contents
     * @todo   Implement testRestore_contents().
     */
    public function testRestore_contents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers manualCart::reset
     * @todo   Implement testReset().
     */
    public function testReset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers manualCart::count_contents
     * @todo   Implement testCount_contents().
     */
    public function testCount_contents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers manualCart::get_quantity
     * @todo   Implement testGet_quantity().
     */
    public function testGet_quantity()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers manualCart::in_cart
     * @todo   Implement testIn_cart().
     */
    public function testIn_cart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers manualCart::remove_all
     * @todo   Implement testRemove_all().
     */
    public function testRemove_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers manualCart::get_product_id_list
     * @todo   Implement testGet_product_id_list().
     */
    public function testGet_product_id_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers manualCart::calculate
     * @todo   Implement testCalculate().
     */
    public function testCalculate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers manualCart::attributes_price
     * @todo   Implement testAttributes_price().
     */
    public function testAttributes_price()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers manualCart::get_products
     * @todo   Implement testGet_products().
     */
    public function testGet_products()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers manualCart::show_total
     * @todo   Implement testShow_total().
     */
    public function testShow_total()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers manualCart::show_weight
     * @todo   Implement testShow_weight().
     */
    public function testShow_weight()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers manualCart::dist_allowed
     * @todo   Implement testDist_allowed().
     */
    public function testDist_allowed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers manualCart::unserialize
     * @todo   Implement testUnserialize().
     */
    public function testUnserialize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
