<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:26:04.
 */
class manualOrderTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var manualOrder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new manualOrder;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers manualOrder::manualOrder
     * @todo   Implement testManualOrder().
     */
    public function testManualOrder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers manualOrder::query
     * @todo   Implement testQuery().
     */
    public function testQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers manualOrder::adjust_zones
     * @todo   Implement testAdjust_zones().
     */
    public function testAdjust_zones()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers manualOrder::adjust_totals
     * @todo   Implement testAdjust_totals().
     */
    public function testAdjust_totals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
