<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:25.
 */
class gpwebpayTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var gpwebpay
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new gpwebpay();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers gpwebpay::gpwebpay
     * @todo   Implement testGpwebpay().
     */
    public function testGpwebpay()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::getServerURL
     * @todo   Implement testGetServerURL().
     */
    public function testGetServerURL()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::update_status
     * @todo   Implement testUpdate_status().
     */
    public function testUpdate_status()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::processGpWebPayResponse
     * @todo   Implement testProcessGpWebPayResponse().
     */
    public function testProcessGpWebPayResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::javascript_validation
     * @todo   Implement testJavascript_validation().
     */
    public function testJavascript_validation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::selection
     * @todo   Implement testSelection().
     */
    public function testSelection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::pre_confirmation_check
     * @todo   Implement testPre_confirmation_check().
     */
    public function testPre_confirmation_check()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::confirmation
     * @todo   Implement testConfirmation().
     */
    public function testConfirmation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::process_button
     * @todo   Implement testProcess_button().
     */
    public function testProcess_button()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::before_process
     * @todo   Implement testBefore_process().
     */
    public function testBefore_process()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::convertToAscii
     * @todo   Implement testConvertToAscii().
     */
    public function testConvertToAscii()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::after_process
     * @todo   Implement testAfter_process().
     */
    public function testAfter_process()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::output_error
     * @todo   Implement testOutput_error().
     */
    public function testOutput_error()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::check
     * @todo   Implement testCheck().
     */
    public function testCheck()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::set_order_status
     * @todo   Implement testSet_order_status().
     */
    public function testSet_order_status()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::install
     * @todo   Implement testInstall().
     */
    public function testInstall()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::remove
     * @todo   Implement testRemove().
     */
    public function testRemove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::keys
     * @todo   Implement testKeys().
     */
    public function testKeys()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::format_raw
     * @todo   Implement testFormat_raw().
     */
    public function testFormat_raw()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::calcGpwebpayMd5Key
     * @todo   Implement testCalcGpwebpayMd5Key().
     */
    public function testCalcGpwebpayMd5Key()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gpwebpay::getSigningErrorMessage
     * @todo   Implement testGetSigningErrorMessage().
     */
    public function testGetSigningErrorMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
