<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:21.
 */
class paypal_pro_payflow_dpTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var paypal_pro_payflow_dp
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new paypal_pro_payflow_dp;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers paypal_pro_payflow_dp::paypal_pro_payflow_dp
     * @todo   Implement testPaypal_pro_payflow_dp().
     */
    public function testPaypal_pro_payflow_dp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::update_status
     * @todo   Implement testUpdate_status().
     */
    public function testUpdate_status()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::javascript_validation
     * @todo   Implement testJavascript_validation().
     */
    public function testJavascript_validation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::selection
     * @todo   Implement testSelection().
     */
    public function testSelection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::pre_confirmation_check
     * @todo   Implement testPre_confirmation_check().
     */
    public function testPre_confirmation_check()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::confirmation
     * @todo   Implement testConfirmation().
     */
    public function testConfirmation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::process_button
     * @todo   Implement testProcess_button().
     */
    public function testProcess_button()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::before_process
     * @todo   Implement testBefore_process().
     */
    public function testBefore_process()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::after_process
     * @todo   Implement testAfter_process().
     */
    public function testAfter_process()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::get_error
     * @todo   Implement testGet_error().
     */
    public function testGet_error()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::check
     * @todo   Implement testCheck().
     */
    public function testCheck()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::install
     * @todo   Implement testInstall().
     */
    public function testInstall()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::remove
     * @todo   Implement testRemove().
     */
    public function testRemove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::keys
     * @todo   Implement testKeys().
     */
    public function testKeys()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::getParams
     * @todo   Implement testGetParams().
     */
    public function testGetParams()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::sendTransactionToGateway
     * @todo   Implement testSendTransactionToGateway().
     */
    public function testSendTransactionToGateway()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::format_raw
     * @todo   Implement testFormat_raw().
     */
    public function testFormat_raw()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::getTestLinkInfo
     * @todo   Implement testGetTestLinkInfo().
     */
    public function testGetTestLinkInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::getTestConnectionResult
     * @todo   Implement testGetTestConnectionResult().
     */
    public function testGetTestConnectionResult()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::templateClassExists
     * @todo   Implement testTemplateClassExists().
     */
    public function testTemplateClassExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::getSubmitCardDetailsJavascript
     * @todo   Implement testGetSubmitCardDetailsJavascript().
     */
    public function testGetSubmitCardDetailsJavascript()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_payflow_dp::sendDebugEmail
     * @todo   Implement testSendDebugEmail().
     */
    public function testSendDebugEmail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
