<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:19.
 */
class paypal_pro_hsTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var paypal_pro_hs
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new paypal_pro_hs;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers paypal_pro_hs::paypal_pro_hs
     * @todo   Implement testPaypal_pro_hs().
     */
    public function testPaypal_pro_hs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::update_status
     * @todo   Implement testUpdate_status().
     */
    public function testUpdate_status()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::javascript_validation
     * @todo   Implement testJavascript_validation().
     */
    public function testJavascript_validation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::selection
     * @todo   Implement testSelection().
     */
    public function testSelection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::pre_confirmation_check
     * @todo   Implement testPre_confirmation_check().
     */
    public function testPre_confirmation_check()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::confirmation
     * @todo   Implement testConfirmation().
     */
    public function testConfirmation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::process_button
     * @todo   Implement testProcess_button().
     */
    public function testProcess_button()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::before_process
     * @todo   Implement testBefore_process().
     */
    public function testBefore_process()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::after_process
     * @todo   Implement testAfter_process().
     */
    public function testAfter_process()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::get_error
     * @todo   Implement testGet_error().
     */
    public function testGet_error()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::check
     * @todo   Implement testCheck().
     */
    public function testCheck()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::install
     * @todo   Implement testInstall().
     */
    public function testInstall()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::remove
     * @todo   Implement testRemove().
     */
    public function testRemove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::keys
     * @todo   Implement testKeys().
     */
    public function testKeys()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::getParams
     * @todo   Implement testGetParams().
     */
    public function testGetParams()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::sendTransactionToGateway
     * @todo   Implement testSendTransactionToGateway().
     */
    public function testSendTransactionToGateway()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::getTransactionDetails
     * @todo   Implement testGetTransactionDetails().
     */
    public function testGetTransactionDetails()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::format_raw
     * @todo   Implement testFormat_raw().
     */
    public function testFormat_raw()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::getTestLinkInfo
     * @todo   Implement testGetTestLinkInfo().
     */
    public function testGetTestLinkInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::getTestConnectionResult
     * @todo   Implement testGetTestConnectionResult().
     */
    public function testGetTestConnectionResult()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::verifyTransaction
     * @todo   Implement testVerifyTransaction().
     */
    public function testVerifyTransaction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paypal_pro_hs::sendDebugEmail
     * @todo   Implement testSendDebugEmail().
     */
    public function testSendDebugEmail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
