<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-28 at 12:25:18.
 */
class sage_pay_serverTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var sage_pay_server
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new sage_pay_server;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers sage_pay_server::sage_pay_server
     * @todo   Implement testSage_pay_server().
     */
    public function testSage_pay_server()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::update_status
     * @todo   Implement testUpdate_status().
     */
    public function testUpdate_status()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::javascript_validation
     * @todo   Implement testJavascript_validation().
     */
    public function testJavascript_validation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::selection
     * @todo   Implement testSelection().
     */
    public function testSelection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::pre_confirmation_check
     * @todo   Implement testPre_confirmation_check().
     */
    public function testPre_confirmation_check()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::confirmation
     * @todo   Implement testConfirmation().
     */
    public function testConfirmation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::process_button
     * @todo   Implement testProcess_button().
     */
    public function testProcess_button()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::before_process
     * @todo   Implement testBefore_process().
     */
    public function testBefore_process()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::after_process
     * @todo   Implement testAfter_process().
     */
    public function testAfter_process()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::get_error
     * @todo   Implement testGet_error().
     */
    public function testGet_error()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::check
     * @todo   Implement testCheck().
     */
    public function testCheck()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::install
     * @todo   Implement testInstall().
     */
    public function testInstall()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::remove
     * @todo   Implement testRemove().
     */
    public function testRemove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::keys
     * @todo   Implement testKeys().
     */
    public function testKeys()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::getParams
     * @todo   Implement testGetParams().
     */
    public function testGetParams()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::sendTransactionToGateway
     * @todo   Implement testSendTransactionToGateway().
     */
    public function testSendTransactionToGateway()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::format_raw
     * @todo   Implement testFormat_raw().
     */
    public function testFormat_raw()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::loadErrorMessages
     * @todo   Implement testLoadErrorMessages().
     */
    public function testLoadErrorMessages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::getErrorMessageNumber
     * @todo   Implement testGetErrorMessageNumber().
     */
    public function testGetErrorMessageNumber()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::getErrorMessage
     * @todo   Implement testGetErrorMessage().
     */
    public function testGetErrorMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::errorMessageNumberExists
     * @todo   Implement testErrorMessageNumberExists().
     */
    public function testErrorMessageNumberExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::formatURL
     * @todo   Implement testFormatURL().
     */
    public function testFormatURL()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::getTestLinkInfo
     * @todo   Implement testGetTestLinkInfo().
     */
    public function testGetTestLinkInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::getTestConnectionResult
     * @todo   Implement testGetTestConnectionResult().
     */
    public function testGetTestConnectionResult()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sage_pay_server::sendDebugEmail
     * @todo   Implement testSendDebugEmail().
     */
    public function testSendDebugEmail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
